accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup_view, name='signup'),
    path('logout/', views.logout_view, name='logout'),
    path('login/', views.login_view, name='login'),
    path('signup/otp/', views.otp, name='otp'),
    path('change_password/', views.change_password, name='change_password'),
]

authwiki_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authwiki_app.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path('users/', include('users.urls')),
    path('library/', include('library.urls')),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='accounts/password/password-resets.html'), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='accounts/password/password-reset-confirms.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="accounts/password/password_reset_confirm.html"), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password/password_reset_complete.html'), name='password_reset_complete'),
]

urlpatterns += staticfiles_urlpatterns()

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.blog_list, name='list'),
    path('blog/create/', views.blog_create, name='create'),
    path('blog/<str:slug>/detail', views.blogs_detail, name="detail"),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from datetime import datetime

class MyUserManager(BaseUserManager):
	def create_user(self, email, username, password=None):
		if not email:
			raise ValueError("Email is required")
		if not username:
			raise ValueError("Username is required")

		user = self.model(
			email = self.normalize_email(email),
			username = username
		)
		user.set_password(password)
		user.save(using=self._db)
		return user

	def create_superuser(self, email, username, password=None):
		user = self.create_user(
			email = self.normalize_email(email),
			username = username,
		)
		user.is_admin = True
		user.is_superuser = True
		user.is_staff = True
		user.set_password(password)
		user.save(using=self._db)
		return user


class MyUser(AbstractBaseUser):
	username = models.CharField(verbose_name="username", max_length=100, unique=True)
	email = models.EmailField(verbose_name="email ", max_length=60, unique=True)
	date_joined = models.DateTimeField(verbose_name = "date_joined", auto_now_add=True)
	last_login = models.DateTimeField(verbose_name="last_login", auto_now_add=True)
	is_admin = models.BooleanField(default = False)
	is_active = models.BooleanField(default = True)
	is_staff = models.BooleanField(default = False)
	is_superuser = models.BooleanField(default=False)
	otp_check = models.BooleanField(default = False)

	USERNAME_FIELD = "email"
	REQUIRED_FIELDS = ['username']

	objects = MyUserManager()

	def __str__(self):
		return self.username

	def has_perm(self, perm, obj=None):
		return True

	def has_module_perms(self, app_label):
		return True

class Profile(models.Model):
    user = models.OneToOneField(MyUser, on_delete=models.CASCADE)
    otp = models.CharField(max_length=6)
    email = models.CharField(max_length=20)
    created_at = models.DateField( default = datetime.now, blank = True)
    updated_at = models.DateField(default= datetime.now, blank = True)


accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError
from django.contrib.auth import authenticate
from accounts.models import MyUser


class UserRegisterForm(UserCreationForm):
    class Meta:
        model = MyUser
        fields = ('email', 'username', 'password1', 'password2')


    def __init__(self, *args, **kwargs):
        
        super(UserRegisterForm, self).__init__(*args, **kwargs)
        for field in (self.fields['email'],self.fields['username'],self.fields['password1'],self.fields['password2']):
            field.widget.attrs.update({'class': 'form-control '})

    def clean_email(self):
        #verifying that the email hasn't been previously registered
        email = self.cleaned_data.get('email')
        qs = MyUser.objects.filter(email=email)
        if qs.exists():
            raise forms.ValidationError("Email is already in use")
        return email

    def clean_password2(self):
       # Check that the two password entries match
       password1 = self.cleaned_data.get("password1")
       password2 = self.cleaned_data.get("password2")
       if password1 and password2 and password1 != password2:
           raise ValidationError("Passwords don't match")
       return password2

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
            return user


class UserAuthenticationForm(forms.ModelForm):
    # form for when user logs in
    password  = forms.CharField(label= 'Password', widget=forms.PasswordInput)

    class Meta:
        model  =  MyUser
        fields =  ('email', 'password')
        widgets = {
                   'email':forms.TextInput(attrs={'class':'form-control'}),
                   'password':forms.TextInput(attrs={'class':'form-control'}),
        }
    def __init__(self, *args, **kwargs):

        super(UserAuthenticationForm, self).__init__(*args, **kwargs)
        for field in (self.fields['email'],self.fields['password']):
            field.widget.attrs.update({'class': 'form-control '})

    def clean(self):
        #verifying your login details
        if self.is_valid():
            email = self.cleaned_data.get('email')
            password = self.cleaned_data.get('password')
            if not authenticate(email=email, password=password):
                raise forms.ValidationError('Invalid Login')
        return email

accounts/views.py
from django.contrib.auth.forms import PasswordChangeForm, PasswordResetForm
from django.shortcuts import render, redirect
from .forms import UserRegisterForm, UserAuthenticationForm
from django.contrib.auth import login, logout, authenticate, update_session_auth_hash
from .models import Profile, MyUser
import random, time
from django.core.mail import send_mail
from django.contrib import messages
from django.http import HttpResponseRedirect, HttpResponse
# Create your views here.

def signup_view(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            email = request.POST.get('email')
            otp = str(random.randint(1000, 9000))
            check_user = MyUser.objects.filter(email = email).first()
            check_profile = Profile.objects.filter(email = email).first()
            if check_user or check_profile:
                 messages.error(request, 'user already exist')
                 return HttpResponseRedirect(request.path_info)
            user = form.save() 
            email    = form.cleaned_data.get('email')
            username = form.cleaned_data.get('username')
            profile = Profile(user = user, otp = otp, email = email)
            profile.save()
            form.save()
            # send the user otp
            send_otp(email, otp)
            request.session['email'] = email
            return redirect('otp/')
        return render(request, 'accounts/signup.html')
    else:
        form = UserRegisterForm()
        return render(request, 'accounts/signup.html')

def logout_view(request):
    logout(request)
    return redirect('/')

def login_view(request):
    user = request.user
    if user.is_authenticated:
        return redirect('/')
    if request.method  == 'POST':
        form = UserAuthenticationForm(request.POST)
        email = request.POST.get('email')
        password = request.POST.get('password')
        user =  authenticate(email=email, password=password)
        # check_profile = Profile.objects.filter(check_otp = False).first()
        # if check_profile:
        #     request.session['email'] = email

        #     return HttpResponseRedirect(request.path_info)
        if user:
            login(request, user)
            return redirect('/')
        messages.info(request, 'Invalid Information. Please Try Again')        
        return render(request, 'accounts/sign_in.html')
    else:
        form = UserAuthenticationForm()
        return render(request, 'accounts/sign_in.html')

def send_otp(email, otp):
    sub = '<p> Welcome to Authwiki. We are thrilled to have you, to make sure your account is protected, please use the attached otp to verify your account. <p>Thank you</p></p>' + otp
    msg = 'Account verification'
    send_mail(
        subject= msg,
        message= "Otp Verification",
        from_email = "AuthWiki <authwiki29@gmail.com>",
        recipient_list = [email],
        html_message= sub
    )
    return None

def otp(request):
    email = request.session['email']
    context = {'email' : email}
    if request.method == "POST":
        otp = request.POST.get('otp')
        profile = Profile.objects.filter(email = email).first()
        if otp == profile.otp:
            return redirect('/accounts/login')
        else:
            Profile.objects.filter(email = email).delete()
            print('Oops')
            messages.error(request, 'Incorrect Otp')
            return HttpResponseRedirect(request.path_info)
    return render(request, 'accounts/otp.html', context)

def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            messages.success(request, 'Your password was successfully updated!')
            return redirect('change_password')
        else:
            messages.error(request, 'Please correct the error below.')
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'accounts/password/password-resets.html', {
        'form': form
    })

templates/accounts/change_password.html
{% extends 'base.html' %}

{% block title %}Change Password Page{% endblock title %}

{% block content %} 
    <h2>Change Password</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <a href="{% url 'home' %}">Back</a>
        <button type="submit">Submit</button>
    </form>
{% endblock content %}

templates/accounts/login.html
{% extends 'base.html' %}
{% load socialaccount %}
{% block content %}
    <form>
        {{form }}
        <div>
        <input type="submit" value="go">
        or 
        <a href="{% provider_login_url 'google' method = 'oauth2' %}">
            <button class="googlesignUp">
              <img
                src="{%static 'images/icons8-google.svg' %}"
                alt="Google logo"
              />
              Sign Up using Google
            </button> </a
          >
          <a href="{% provider_login_url 'github' method = 'oauth2' %}">
            <button class="googlesignUp">
              <img
                src="{%static 'images/icons8-github.svg' %}"
                alt="Google logo"
              />
              Sign Up using Github
            </button> </a
          >
        </div>
    </form>
{% endblock %}

templates/accounts/otp.html
     {% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/signup.css' %}">
    <script src="https://use.fontawesome.com/45ba5e599a.js"></script>
</head>

<body>
    <div class="wrapper">
        <header>
            <a href="#"><img class="logoimg" src="{% static 'images/IMG_1543.jpg' %}" alt="logo icon"></a>
            <a href=""><img class="lang" src="{% static 'images/icons8-geography-50.png' %}" alt="language icon"></a>
            <div>
                <a href="">Otp Verification</a>
            </div>
        </header>
        <main>
            <div>
                <form action=" {% url 'accounts:otp' %}" method="POST">
                    {% csrf_token %}
                    <div class="h2div">
                        <h2>Verify your account</h2>
                    </div>
                    {% for message in messages %}

                    <div class="alert alert-success">
                        <a class="close" href="#" data-dismiss="alert">×</a> {{ message }}
                    </div>

                    {% endfor %}
                    <div class="usernamediv">
                        <p class="namep">OTP</p>
                        <input type="number" name="otp" id="" placeholder="Enter your OTP">
                    </div>
                    <div>
                        <button type="submit" class="getbutton">verify</button>
                    </div>
                </form>
            </div>
        </main>
    </div>
    <script src="{%static 'js/script.js' %}"></script>
</body>

</html>

templates/accounts/sign_in.html
{% load static %}
{% load socialaccount %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'css/sign_in.css' %}" />
    <script src="https://use.fontawesome.com/45ba5e599a.js"></script>
    <title>Welcome to AuthWiki || Login</title>
  </head>
  <body>
    <div class="wrapper">
      <header>
        <a class="logo-link" href="#"
          ><img
            class="logoimg"
            src="{% static 'images/logo.png' %}"
            alt="logo icon"
          />
        </a>
        <a href=""
          ><img
            class="lang"
            src="{% static 'images/world.png' %}"
            alt="language icon"
          />
        </a>
        <div class="sign-up">
          <a href="{%url 'accounts:signup'%}">Sign up</a>
        </div>
      </header>
      <main>
        <div>
          <form action=" " method="POST">
            {%csrf_token%}
            <div class="h2div">
              <h2>Sign in</h2>
            </div>
            {%for err in messages %}
            <br />
            <h5 style="color: red" ;>{{err}}</h5>
            {% endfor %}
            <div class="emaildiv">
              <p class="emailp">Email</p>
              <input
                type="email"
                name="email"
                id=""
                placeholder="example@authwiki.com"
              />
            </div>
            <div class="passdiv">
              <p class="passp">Password</p>
              <input
                type="password"
                name="password"
                id="myInput"
                placeholder="Enter password"
              />
              <span class="eye" onclick="myFunction()">
                <i id="hide1" class="fa fa-eye"></i>
                <i id="hide2" class="fa fa-eye-slash"></i>
              </span>
            </div>
            <div>
              <button type="submit" class="getbutton">Sign in</button>
            </div>
            <div class="forgotpass">
              <a href="{%url 'password_reset'%}">Forgot your password?</a>
            </div>
          </form>
        </div>
        <div class="logusingdiv">
          <p class="orsignupwith">or sign in with:</p>
          <a href="{% provider_login_url 'google' method = 'oauth2' %}">
            <button class="googlesignUp">
              <img
                src="{%static 'images/icons8-google.svg' %}"
                alt="Google logo"
              />
              Login using Google
            </button> </a
          >
          <br />
          <a href="{% provider_login_url 'github' method = 'oauth2' %}">
          <button class="applesignUP">
            <img src="{%static 'images/github.svg' %}" alt="Apple logo" /> Sign
            in using GitHub
          </button> 
        </a>
        </div>
        <a href="#" class="m-login"
          >Don't have an account yet ? <i class="fa fa-arrow-right"></i>
        </a>
      </main>
    </div>
    <script src="{% static 'js/script.js' %}"></script>
  </body>
</html>

templates/accounts/signup.html
{% load static %} {% load socialaccount %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>AuthWiki</title>
    <link rel="stylesheet" href="{% static 'css/signup.css' %}" />
    <script src="https://use.fontawesome.com/45ba5e599a.js"></script>
  </head>
  <body>
    <div class="wrapper">
      <header>
        <a href="#"
          ><img
            class="logoimg"
            src="{%static 'images/IMG_1543.jpg' %}"
            alt="logo icon"
        /></a>
        <a href=""
          ><img
            class="lang"
            src="{%static 'images/icons8-geography-50.png' %}"
            alt="language icon"
        /></a>
        <div>
          <a href="{%url 'accounts:login'%}">Sign in</a>
        </div>
      </header>
      <main>
        <div>
          <!-- Sign up form starts -->
          <form action="" method="POST">
            {% csrf_token %}
            <div class="h2div">
              <h2>Get started today</h2>
            </div>
            <div class="usernamediv">
              <p class="namep">Username</p>
              <input type="text" name="username" id="" placeholder="John Doe" />
              {%for err in form.username.errors %}
              <small>{{err}}</small>
              {% endfor %}
            </div>
            <div class="emaildiv">
              <p class="emailp">Work Email</p>
              <input
                type="email"
                name="email"
                id=""
                placeholder="johndoe@authwiki.com"
              />
              {%for err in form.email.errors %}
              <small>{{err}}</small>
              {% endfor %}
            </div>
            <div class="passdiv">
              <p class="passp">Password</p>
              <input
                type="password"
                name="password1"
                id="myInput"
                placeholder="Enter password"
              />
              <span class="eye" onclick="myFunction()">
                <i id="hide1" class="fa fa-eye"></i>
                <i id="hide2" class="fa fa-eye-slash"></i>
              </span>
              {%for err in form.password1.errors %}
              <small>{{err}}</small>
              {% endfor %}
            </div>
            <div class="comfirmpassdiv">
              <p class="comfirmpassp">Comfirm Password</p>
              <input
                type="password"
                name="password2"
                id="secmyInput"
                placeholder="Comfirm Password"
              />
              <span class="eye" onclick="comfirmfunction()">
                <i id="comfirmhide1" class="fa fa-eye"></i>
                <i id="comfirmhide2" class="fa fa-eye-slash"></i>
              </span>
              {%for err in form.password2.errors %}
              <small>{{err}}</small>
              {% endfor %}
            </div>
            <div>
              <button type="submit" class="getbutton">Get started now</button>
            </div>
            <!-- checkbox -->
            <div class="firstcheckbox">
              <label for="myCheckboxId" class="checkbox">
                <input
                  class="checkbox__input"
                  type="checkbox"
                  name="myCheckboxName"
                  id="myCheckboxId"
                />
                <div class="checkbox__box"></div>
                I agree to Auth Wiki Terms and Privacy Policy.
              </label>
            </div>
            <br />
            <div class="secondcheckbox">
              <label for="myCheckboxId2" class="checkbox2">
                <input
                  class="checkbox__input2"
                  type="checkbox"
                  name="myCheckboxName2"
                  id="myCheckboxId2"
                />
                <div class="checkbox__box2"></div>
                I agree to receive Auth Wiki news and updates.
              </label>
            </div>
          </form>
          <!-- Sign up form ends -->
          <div class="sign_up_with">
            <p class="orsignupwith">or sign up with:</p>
            <a href="{% provider_login_url 'google' method = 'oauth2' %}">
              <button class="googlesignUp">
                <img
                  src="{%static 'images/icons8-google.svg' %}"
                  alt="Google logo"
                />
                Sign Up using Google
              </button> </a
            ><br />
            <a href="{% provider_login_url 'github' method = 'oauth2' %}">
              <button class="applesignUP">
                <img
                  src="{%static 'images/icons8-github.svg' %}"
                  alt="Apple logo"
                />
                Sign Up using GitHub
              </button>
            </a>
          </div>
        </div>
      </main>
    </div>
    <script src="{%static 'js/scriptlogin.js' %}"></script>
  </body>
</html>