accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup_view, name='signup'),
    path('logout/', views.logout_view, name='logout'),
    path('login/', views.login_view, name='login'),
    path('signup/otp/', views.otp, name='otp'),
    path('change_password/', views.change_password, name='change_password'),
]

authwiki_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authwiki_app.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path('users/', include('users.urls')),
    path('library/', include('library.urls')),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='accounts/password/password-resets.html'), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='accounts/password/password-reset-confirms.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="accounts/password/password_reset_confirm.html"), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password/password_reset_complete.html'), name='password_reset_complete'),
]

urlpatterns += staticfiles_urlpatterns()

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.blog_list, name='list'),
    path('blog/create/', views.blog_create, name='create'),
    path('blog/<str:slug>/detail', views.blogs_detail, name="detail"),
]

library/urls.py
from django.urls import path
from .views import (
    LibraryView,
    PostListView,
    PostDetailView,
    PostCreateView,
    PostUpdateView,
    PostDeleteView,
    postpreference,
    )

from .import views

app_name = 'library'

urlpatterns = [
    path('', LibraryView.as_view(), name='home'),
    path('category/<str:name>', PostListView.as_view(), name='library-category'),
    path('library/new/', PostCreateView.as_view(), name='post-create'),
    path('detail/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
    path('library/<int:pk>/update/', PostUpdateView.as_view(), name='post-update'),
    path('library/<int:pk>/del/', PostDeleteView.as_view(), name='post-delete'),
    path('library/<int:postid>/preference/<int:userpreference>', postpreference, name='postpreference'),

]

blog/models.py
from django.db import models
from accounts.models import MyUser


import uuid
import os


def get_image_path(instance, filename):
    ext = filename.split('.')[-1]
    filename = "%s.%s" % (uuid.uuid4(), ext)
    return os.path.join('blog_pics', filename)


# # Create your models here.
class Blog(models.Model): 

    title = models.CharField(max_length=100)
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add = True)
    thumb = models.FileField(upload_to=get_image_path, null=True, blank=True, default='default.jpg')
    author = models.ForeignKey(MyUser, default=None, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def snippet(self):
        return self.body[:60]+'...'

blog/forms.py
from django import forms
from .import models

class CreateBlog(forms.ModelForm):
    class Meta:
        model = models.Blog
        fields = ['title', 'body', 'slug', 'thumb']

blog/views.py
from django.shortcuts import render, redirect
from .models import Blog
from django.contrib.auth.decorators import login_required
from . import forms
from django.utils import timezone
from accounts.models import MyUser

# Create your views here.
def blog_list(request):
    blogs = Blog.objects.all().order_by('date')
    return render(request,'blog/blog_list.html', {'blogs':blogs})

def blogs_detail(request, slug):
    blogs = Blog.objects.get(slug=slug)
    print(blogs)
    return render(request, 'blog/blog_detail.html', {'blogs':blogs})

@login_required(login_url='/accounts/login')
def blog_create(request):
    if request.method == 'POST':
        form = forms.CreateBlog(request.POST, request.FILES)
        if form.is_valid():
            # save blog to db
            instance = form.save(commit=False)
            instance.author = request.user
            instance.save()
            return redirect('blog:list')
    else:
        form = forms.CreateBlog()
    return render(request, 'blog/blog_create.html', {'form':form})

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Authwiki_team2</title>
    <link
      href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;300;400;500;700&display=swap"
      rel="stylesheet" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <!-- tailwind -->
    <link
      rel="stylesheet"
      href="https://unpkg.com/flowbite@1.5.2/dist/flowbite.min.css"
    />
    <script src="https://unpkg.com/flowbite@1.5.2/dist/flowbite.js"></script>
    <link rel="stylesheet" href="{%static 'css/header.css' %}" / >
    <link rel="stylesheet" href="{%static 'css/style.css' %}" />
  </head>
  <body>
    <nav class="navbar navbar-light navbar-expand-lg">
      <div class="container">
        <a class="navbar-brand" href=""><img class="nav-image" src="{%static 'images/logo.png' %}" /></a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav pt-2 w-100 nav-me-fill pl-5  mb-2 mb-lg-0 ">
            <li class="nav-item pr-4 pl-5">
              <a class="nav-link" href="{%url 'index' %}">Home</a>
            </li>
            <li class="nav-item pr-4 pl-5 ">
              <a class="nav-link" href="{%url 'library:home' %}">Library</a>
            </li>
           <li class="nav-item pl-5 pr-4">
              <!--devs and docs  dropdown -->
              <button
                id="dropdownNavbarLink1"
                data-dropdown-toggle="dropdownNavbar1"
                class="flex dropdown justify-between  items-center   w-full font-medium text-gray-700  "
              >
                <span class="nav-link ">Devs and Docs</span>
                <svg
                  class="ml-1 w-5 h-5"
                  aria-hidden="true"
                  fill="currentColor"
                  viewBox="0 0 20 20"
                  xmlns="http://www.w3.org/2000/svg"
                >
                  <path
                    fill-rule="evenodd"
                    d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z"
                    clip-rule="evenodd"
                  ></path>
                </svg>
              </button>

              <!-- Dropdown menu -->
              <div
                id="dropdownNavbar1"
                class="z-10 w-50 hidden bg-white rounded divide-y divide-gray-100 shadow dark:bg-gray-700 dark:divide-gray-600 block text-2xl"
                style="
                  position: absolute;
                  inset: 0px auto auto 0px;
                  margin: 0px;
                  transform: translate(381px, 66px);
                "
                data-popper-reference-hidden=""
                data-popper-escaped=""
                data-popper-placement="bottom"
              >
                <div class="grid lg:grid-cols-2 w-76">
                  <div class="mx-5 lg:m-5 pt-5">
                    <ul
                      class="py-1 m-6 w-4 text-sm text-gray-700 dark:text-gray-200"
                      aria-labelledby="dropdownLargeButton"
                    >
                      <li class="flex py-4 drop-text">
                        <div class="">
                          <img src="{%static 'images/Blog.png' %}" alt="" />
                        </div>

                        <a
                          href="{%url 'blog'%}"
                          class="block font-bold drop_text text-[#000] text-2xl px-4"
                          >Blog</a
                        />
                      </li>
                      <li class="flex py-4">
                        <div class="">
                          <img src="{%static 'images/Document.png' %}" alt="" />
                        </div>

                        <a
                          href="{%url 'service' %}"
                          class="block font-bold drop_text text-[#000] text-md px-4 "
                          >Our Servies</a
                        >
                      </li>
                      <li class="flex py-4">
                        <div class="">
                          <img src="{%static 'images/Technical Support.png' %}" alt="" />
                        </div>

                        <a
                          href="{%url 'support' %}"
                          class="block drop_text font-bold text-[#000] text-md px-4 "
                          >Get Support</a
                        >
                      </li>
                      <li class="flex py-3">
                        <div class="">
                          <img src="{%static 'images/FAQ.png' %}" alt="" />
                        </div>
                        <a
                          href="{%url 'faq'%}"
                          class="block drop_text font-bold text-[#000] text-md px-4"
                          >FAQs</a
                        >
                      </li>
                    </ul>
                  </div>

                  <div class="hidden lg:grid vl"></div>
                  <!-- img -->
                  <div class="py-0 latest_text px-md-4  lg:my-5 w text-md-left text-sm-center">
                    <a
                      href=""
                      class="block py-4  font-semibold text-md-xl text-[#151515] dark:hover:bg-gray-600  dark:hover:text-black"
                      >Latest from our Blog</a
                    >
                    <img class="w-sm-30" src="{%static 'images/Rectangle 1130.png' %}">
                    <p class="text-[#002530]  py-4">
                      Microsoft moves to new Windows development cycle with
                      major release every three years, feature drops in between.
                      <span class="text-red-500">Read more</span>
                    </p>
                  </div>
                </div>
              </div>
            </li>     
            <!-- company dropdown -->
            <li class="nav-item pr-4  pl-5">
              <button
                id="dropdownNavbarLink"
                data-dropdown-toggle="dropdownNavbar"
                class="flex dropdown justify-between items-center w-full "
              >
                <span class="nav-link">Company</span>
                <svg
                  class="ml-1 w-5 h-5"
                  aria-hidden="true"
                  fill="currentColor"
                  viewBox="0 0 20 20"
                  xmlns="http://www.w3.org/2000/svg"
                >
                  <path
                    fill-rule="evenodd"
                    d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z"
                    clip-rule="evenodd"
                  ></path>
                </svg>
              </button>

              <!-- Dropdown menu -->
              <div
                id="dropdownNavbar"
                class="z-10 w-50 hidden bg-white rounded divide-y divide-gray-100 shadow dark:bg-gray-700 dark:divide-gray-600 block"
                style="
                  position: absolute;
                  inset: 0px auto auto 0px;
                  margin: 0px;
                  transform: translate(381px, 66px);
                "
                data-popper-reference-hidden=""
                data-popper-escaped=""
                data-popper-placement="bottom"
              >
                <div class="grid lg:grid-cols-2 w-76">
                  <div class="m-5 image_about py-0  lg:my-5 w">
                    <img src="  {%static 'images/Frame 2414.png' %}" alt="" />
                  </div>
                  <!-- <hr> -->
                  <div class="hidden lg:grid v2"></div>
                  <!-- img -->
                  <div class="order-last mx-5 lg:m-5 p-">
                    <ul
                      class="py-1 m-6 text-sm text-gray-700 dark:text-gray-200"
                      aria-labelledby="dropdownLargeButton"
                    >
                      <li class="flex py-4">
                        <div class="">
                          <img src="{%static 'images/logo-svgrepo-com 1.png' %}" alt="" />
                        </div>
                        <a
                          href="{%url 'about'%}"
                          class="block font-bold text-[#000] text-md px-4 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white"
                          >About Us</a
                        >
                      </li>
                      <li class="flex py-4">
                        <div class="">
                          <img src="{%static 'images/Management.png' %}" alt="" />
                        </div>

                        <a
                          href="{%url 'teams'%}"
                          class="block font-bold text-[#000] text-md px-4 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white"
                          >Teams</a
                        >
                      </li>
                      <li class="flex py-4">
                        <div class="">
                          <img src="{%static 'images/Laugh.png' %}" alt="" />
                        </div>
                        <a
                          href=""
                          class="block font-bold text-[#000] text-md px-4 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white"
                          >Customers</a
                        >
                      </li>
                      <li class="flex py-3">
                        <div class=""><img src="{%static 'images/Goal.png' %}" alt="" /></div>
                        <a
                          href="{%url 'contact'%}"
                          class="block font-bold text-[#000] text-md px-4 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white"
                          >Contact</a
                        >
                      </li>
                    </ul>
                  </div>
                </div>
              </div>
            </li>
            {% if user.is_authenticated%}
            <li class="nav-item pr-4 pl-5">
              <a
                href="{%url 'accounts:logout'%}"
                class="btn button-2"
                tabindex="-1"
                role="button"
                >Logout</a
              >
            </li>
            {% else %}
            <li class="nav-item pr-4 pl-5">
              <a
                href="{%url 'accounts:login' %}"
                class="btn button-2"
                tabindex="-1"
                role="button"
                >Login</a
              >
            </li>
            <li class="nav-item pr-4 pl-5">
              <a
                href="{%url 'accounts:signup'%}"
                class="btn  button-1"
                tabindex="-1"
                role="button"
                >Sign Up</a
              >
            </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>
    {%block content %}
    {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

</html>

templates/base2.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>          
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;300;400;500;700&display=swap" rel="stylesheet" />
  <link rel="stylesheet" href="{%static 'css/base2.css' %}">
  <link
  rel="stylesheet"
  href="https://unpkg.com/flowbite@1.5.2/dist/flowbite.min.css"
/>
  <script src="https://unpkg.com/flowbite@1.5.2/dist/flowbite.js"></script>
  <link rel="stylesheet" href="{%static 'css/style.css' %}" />
  {% block extra_css %} {% endblock %}
</head>
<body>
   <div>
    <nav class="navbar navbar-expand-lg navbar-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="#"><img src="{%static 'images/Auth Wiki Logo.png' %}"></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-4">
            <li class="text-center pt-2">
              <a class="nav-link header_link links" aria-current="page" href="{%url 'index'%}">Home</a>
            </li>
            <li class="text-center pt-2">
              <a class="nav-link header_link links " href="{%url 'library:home'%}">Library</a>
            </li>
            <li class=" text-center pt-2">
              <!--devs and docs  dropdown -->
              <button
                id="dropdownNavbarLink1"
                data-dropdown-toggle="dropdownNavbar1"
                class="flex dropdown justify-between  items-center   w-full font-medium text-gray-700  "
              >
                <span class="nav-link pr-4">Devs and Docs</span>
                <svg
                  class="ml-1 w-5 h-5"
                  aria-hidden="true"
                  fill="currentColor"
                  viewBox="0 0 20 20"
                  xmlns="http://www.w3.org/2000/svg"
                >
                  <path
                    fill-rule="evenodd"
                    d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z"
                    clip-rule="evenodd"
                  ></path>
                </svg>
              </button>

              <!-- Dropdown menu -->
              <div
                id="dropdownNavbar1"
                class="z-10 w-50 hidden bg-white rounded divide-y divide-gray-100 shadow dark:bg-gray-700 dark:divide-gray-600 block text-2xl"
                style="
                  position: absolute;
                  inset: 0px auto auto 0px;
                  margin: 0px;
                  transform: translate(381px, 66px);
                "
                data-popper-reference-hidden=""
                data-popper-escaped=""
                data-popper-placement="bottom"
              >
                <div class="grid lg:grid-cols-2 w-76">
                  <div class="mx-5 lg:m-5 pt-5">
                    <ul
                      class="py-1 m-6 text-sm text-gray-700 dark:text-gray-200"
                      aria-labelledby="dropdownLargeButton"
                    >
                      <li class="flex py-4 drop-text">
                        <div class="">
                          <img src="{%static 'images/Blog.png' %}" alt="" />
                        </div>

                        <a
                          href="{%url 'blog'%}"
                          class="block font-bold drop_text text-[#000] text-2xl px-4"
                          >Blog</a
                        />
                      </li>
                      <li class="flex py-4">
                        <div class="">
                          <img src="{%static 'images/Document.png' %}" alt="" />
                        </div>

                        <a
                          href="{%url 'service' %}"
                          class="block font-bold drop_text text-[#000] text-md px-4 "
                          >Our Servies</a
                        >
                      </li>
                      <li class="flex py-4">
                        <div class="">
                          <img src="{%static 'images/Technical Support.png' %}" alt="" />
                        </div>

                        <a
                          href="{%url 'support' %}"
                          class="block drop_text font-bold text-[#000] text-md px-4 "
                          >Get Support</a
                        >
                      </li>
                      <li class="flex py-3">
                        <div class="">
                          <img src="{%static 'images/FAQ.png' %}" alt="" />
                        </div>
                        <a
                          href="{%url 'faq'%}"
                          class="block drop_text font-bold text-[#000] text-md px-4"
                          >FAQs</a
                        >
                      </li>
                    </ul>
                  </div>

                  <div class="hidden lg:grid vl"></div>
                  <!-- img -->
                  <div class="py-0 latest_text px-md-4  lg:my-5 w text-md-left text-sm-center">
                    <a
                      href=""
                      class="block py-4  font-semibold text-md-xl text-[#151515] dark:hover:bg-gray-600  dark:hover:text-black"
                      >Latest from our Blog</a
                    >
                    <img src="{%static 'images/Rectangle 1130.png' %}">
                    <p class="text-[#002530]  py-4">
                      Microsoft moves to new Windows development cycle with
                      major release every three years, feature drops in between.
                      <span class="text-red-500">Read more</span>
                    </p>
                  </div>
                </div>
              </div>
            </li>     
            <li class="nav-link text-center"> <button class="btn_1 header_link"><a class="anchor-text" href="">Go to community</a> </button></li>
          </ul>
        </div>
        <div class="d-flex gap-3 m-sm-auto nav-link">    
          <div class=""> <img class="image_icon header_link" src="{%static 'images/search.png' %}"></div>
          <div class=""><img class="image_icon header_link" src="{%static 'images/notification.png' %}"></div> 
          <div class="profile_img">
            <img class="image_icon rounded-circle " src="{%static 'images/person3.png'%}" alt="profile image">
          </div>     
        </div>

    </nav>
  </div> 
  {% block content %}
  {% endblock %}
   <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
</body>
</body>
<body class="{%block body_class%}{% endblock %}"></body> 
</html>

templates/footer.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <link
      href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;300;400;500;700&display=swap"
      rel="stylesheet"
    />

    <script
      src="https://kit.fontawesome.com/f73f014758.js"
      crossorigin="anonymous"
    ></script>
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
    />
    <meta name="viewport" content="width=<device-width>, initial-scale=1.0" />
    <link rel="stylesheet" href="{%static 'css/footer.css' %}" />
    <title>Document</title>
  </head>
  <body>
    <footer>
      <img class="image" src="{%static 'images/footerlogo.png' %}" alt="" />

      <div class="footer-div">
        <div class="first-div">
          <div class="footer-sections Library">
            <h3><a href="{%url 'library:home'%}">Library</a></h3>
          </div>
          <div class="footer-sections community">
            <h3><a href="">Community</a></h3>
          </div>
          <div class="footer-sections">
            <h3>Devs and Docs</h3>
            <p><a href="{%url 'blog' %}">Blog</a></p>
            <p><a href="{%url 'doc'%}">Documentation</a></p>
            <p><a href="{%url 'support' %}">Get Support</a></p>
            <p><a href="{%url 'faq' %}">FAQS</a></p>
          </div>
          <div class="footer-sections">
            <h3>Company</h3>
            <p><a href="{%url 'about' %}">About Us</a></p>
            <p><a href="{%url 'teams'%}">Teams</a></p>
            <p><a href="">Customers</a></p>
            <p><a href="">Careers</a></p>
          </div>
          <div class="footer-sections">
            <h3><a href="">industries</a></h3>
            <p><a href="">Financial Services</a></p>
            <p><a href="">HealthCare</a></p>
            <p><a href="">Social Media</a></p>
            <p><a href="">Retail</a></p>
            <p><a href="">Public Sector</a></p>
          </div>
        </div>
        <div class="last-div">
          <h3>Our socials</h3>
          <div class="footer-icons">
            <a href="#"><i class="fas fa-globe fa-lg right-side1-icons"></i></a>
            <a href="#"
              ><i class="fab fa-facebook fa-lg right-side1-icons"></i
            ></a>
            <a href="#"
              ><i class="fab fa-twitter fa-lg right-side1-icons"></i
            ></a>
            <a href="#"
              ><i class="fab fa-instagram fa-lg right-side1-icons"></i
            ></a>
            <a href="#"
              ><i class="fab fa-github fa-lg right-side1-icons"></i
            ></a>
          </div>
        </div>
      </div>
      <div class="divider"></div>
      <div class="footer-bottom">
        <p><a href="">Privacy Policy</a></p>
        <p><a href="">Terms of Use</a></p>
        <p><a href="">Disclaimer</a></p>
        <p><a href="">Legal</a></p>
        <p><a href="">Site Map</a></p>
        <p class="copyright">c 2022 Auth Wiki. All rights reserved</p>
      </div>
    </footer>
  </body>
</html>

templates/sign_in.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../static\css\sign_in.css">
    <script src="https://use.fontawesome.com/45ba5e599a.js"></script>
    <title>Welcome to AuthWiki || Login </title>
</head>
<body>
    <div class="wrapper">
    <header>
        <a class="logo-link" href="#"><img class="logoimg" src="../static\images\logo.png" alt="logo icon"> </a>
       <a href=""><img class="lang" src="../static\images\icons8-geography-50.png" alt="language icon"> </a>
        <div class="sign-up">
            <a href="">Sign up</a>
        </div>
    </header>
    <main>
        <div>
            <form action="">
                <div class="h2div">
                    <h2>Sign in</h2>
                </div>
                <div class="emaildiv">
                    <p class="emailp">Email</p>
                    <input type="email" name="email" id="" placeholder="example@authwiki.com">
                </div>
                <div class="passdiv">
                    <p class="passp">Password</p>
                    <input type="password" name="password" id="myInput" placeholder="Enter password">
                    <span class="eye" onclick="myFunction()">
                    <i id="hide1" class="fa fa-eye"></i>
                    <i id="hide2" class="fa fa-eye-slash"></i>
                    </span>
                </div>
                <div>
                    <button type="submit" class="getbutton">Sign in</button>
                </div>
                <div class="forgotpass">
                    <a href="#">Forgot your password?</a>
                </div>
            </form>
        </div>
        <div class="logusingdiv"> 
            <p class="orsignupwith">or sign in with:</p>
            <button class="googlesignUp"> <img class="googlelogo" src="../static\images\icons8-google.svg" alt="Google logo"> Sign in using Google</button><br>
            <button class="applesignUP"> <img src="../static\images\icons8-github.svg" alt="Apple logo"> Sign in using GitHub</button>
        </div>
        <a href="" class="m-login" >Don't have an account yet ?  <i class="fa fa-arrow-right"></i>  </a>
    </main>
</div>
     <script src="../static\js\sign_in.js"></script>

</body>
</html>

templates/user-landing.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="./static/css/user-landing.css">
    <title>Document</title>
</head>
<body>
    <section class="user-landing-page">
        <div class="user-langing-banner-cover">
            <img src="./static/images/user-landing-page-banner.png" alt="">
        </div>
        
        <div class="user-landing-intro">
            <h3>Auth Wiki very versatile and modular, and it can be seamlessly integrated into any online application.
                Auth Wiki codes are easy to implement and easily adaptable.</h3>
           <p>A wide range of authentication methods are available, including login and password for the different languages and frameworks,
                as well as Facebook, Twitter, and others.</p>
        </div>
        
        <div class="user-landing-get-library">
            <p>Varieties of code Languages to download from</p>
            <a href="#">Go To Code Library</a>
        </div>
    </section>
</body>
</html>