accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup_view, name='signup'),
    path('logout/', views.logout_view, name='logout'),
    path('login/', views.login_view, name='login'),
    path('signup/otp/', views.otp, name='otp'),
    path('change_password/', views.change_password, name='change_password'),
]

authwiki_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authwiki_app.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path('users/', include('users.urls')),
    path('library/', include('library.urls')),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='accounts/password/password-resets.html'), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='accounts/password/password-reset-confirms.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="accounts/password/password_reset_confirm.html"), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password/password_reset_complete.html'), name='password_reset_complete'),
]

urlpatterns += staticfiles_urlpatterns()

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.blog_list, name='list'),
    path('blog/create/', views.blog_create, name='create'),
    path('blog/<str:slug>/detail', views.blogs_detail, name="detail"),
]

users/urls.py
from django.urls import re_path, include
from . import views

app_name = 'users'

urlpatterns = [
    re_path('profile', views.profile, name='profile'),
    re_path('update', views.update, name='update'),
]

users/models.py
from django.db import models
from django import forms
from PIL import Image
from accounts.models import MyUser


from django.conf import settings
from django.db import models

import uuid
import os

def get_image_path(instance, filename):
    ext = filename.split('.')[-1]
    filename = "%s.%s" % (uuid.uuid4(), ext)
    return os.path.join('profile_pics', filename)

def get_cover_path(instance, filename):
    ext = filename.split('.')[-1]
    filename = "%s.%s" % (uuid.uuid4(), ext)
    return os.path.join('cover_pics', filename)


class UserProfile(models.Model):
    user = models.OneToOneField(MyUser, on_delete=models.CASCADE)
    first_name = models.CharField(verbose_name='first_name', max_length=150, default=0000)
    middle_name = models.CharField(verbose_name='middle_name', max_length=150, default=0000)
    last_name = models.CharField(verbose_name='last_name', max_length=150, default=0000)
    position = models.CharField(verbose_name='position', max_length=300,  default='')
    image = models.FileField(upload_to=get_image_path, null=True, blank=True, default='default.jpg')
    cover = models.FileField(upload_to=get_cover_path, null=True, blank=True, default='default.jpg')
    bio = models.TextField(verbose_name='bio', max_length=500,  default='')
    # portfolio = models.TextField(verbose_name='portfolio', max_length=350,  default='')
    city = models.CharField(verbose_name='city', max_length=30, default='')
    country = models.CharField(verbose_name='country', max_length=50, default='')
    website  = models.URLField(max_length=500, null=True, blank=True,)
    facebook = models.URLField(max_length=500, null=True, blank=True,)
    twitter = models.URLField(max_length=500, null=True, blank=True,)
    instagram = models.URLField(max_length=500, null=True, blank=True,)
    github = models.URLField(max_length=500, null=True, blank=True,)



    def __str__(self):
        return f'{self.user.username} User Profile'

    def save(self, *args, **kwargs):
        super(UserProfile, self).save(*args, **kwargs)

        img = Image.open(self.image.path)

        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)
    

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import UserProfile
from accounts.models import MyUser


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = MyUser

        fields = ['username','email']


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['first_name','middle_name','last_name','position','image','cover','bio','city','country','website','facebook','twitter','instagram','github']

users/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import UserUpdateForm, ProfileUpdateForm

def is_users(profile_user, logged_user):
    return profile_user == logged_user

# Create your views here.
@login_required
def profile(request):
    u_form = UserUpdateForm(instance=request.user)
    p_form = ProfileUpdateForm(instance=request.user.userprofile)
    context = {
        'u_form': u_form,
        'p_form': p_form,
    }

    return render(request, 'users/profile.html', context)

@login_required
def update(request):
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST,
                                   request.FILES,
                                   instance=request.user.userprofile)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, f'Your account has been updated!')
            return redirect('users:profile')

    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.userprofile)

    context = {
        'u_form': u_form,
        'p_form': p_form
    }

    return render(request, 'users/update.html', context)

templates/users/profile.html
{% extends "base.html" %}
{% block content %}
<div>
  <div>
    <img src="{{ user.userprofile.cover.url }}"></a>
    <a href="{{ user.userprofile.image.url }}"><img src="{{ user.userprofile.image.url }}"></a>
    <h1>{{ user.first_name }} {{ user.middle_name }} {{ user.last_name }}<h1>
    <p>{{ user.userprofile.position }}</p>
    <p>----Portfolio needs a little research to implement----</p>
    <h3>Bio</h3>
    <p>{{ user.userprofile.bio }}</p>
    <h1><a href="{% url 'users:update' %}">Edit Profile</a></h1>
    <p><a href="{{ user.userprofile.website }}"> {{ user.userprofile.website }} </a></p>
    <p><a href="{{ user.userprofile.facebook }}"> {{ user.userprofile.facebook }} </a></p>
    <p><a href="{{ user.userprofile.twitter }}"> {{ user.userprofile.twitter }} </a></p>
    <p><a href="{{ user.userprofile.instagram }}"> {{ user.userprofile.instagram }} </a></p>
    <p><a href="{{ user.userprofile.github }}"> {{ user.userprofile.github }} </a></p>

    <p>{{ user.userprofile.city }}, {{ user.userprofile.city }}</p>

    {% if user.is_user%}
    <a href="#"><img src="REPORT"></a>
    
    {% else %}
    <div class="d-flex gap-5 p-4">
      <div class="mx-auto">
        <button class="btn btn-2 bg-white login-btn" type="submit">
          <a href="{%url 'accounts:logout'%}">LOG OUT</a>
        </button>
      </div>
    </div>
    {% endif %}
    
  

  



{% endblock content %}

templates/users/update.html
{% extends "base.html" %}
{% block content %}
<div>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <fieldset>
            <legend>Profile Info</legend>
            {{ u_form }}
            {{ p_form }}
        </fieldset>
        <div>
            <button type="submit">Update</button>
        </div>
    </form>
  </div>
{% endblock content %}