authwiki_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authwiki_app.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path('users/', include('users.urls')),
    path('library/', include('library.urls')),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='accounts/password/password-resets.html'), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='accounts/password/password-reset-confirms.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="accounts/password/password_reset_confirm.html"), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password/password_reset_complete.html'), name='password_reset_complete'),
]

urlpatterns += staticfiles_urlpatterns()

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.blog_list, name='list'),
    path('blog/create/', views.blog_create, name='create'),
    path('blog/<str:slug>/detail', views.blogs_detail, name="detail"),
]

library/urls.py
from django.urls import path
from .views import (
    LibraryView,
    PostListView,
    PostDetailView,
    PostCreateView,
    PostUpdateView,
    PostDeleteView,
    postpreference,
    )

from .import views

app_name = 'library'

urlpatterns = [
    path('', LibraryView.as_view(), name='home'),
    path('category/<str:name>', PostListView.as_view(), name='library-category'),
    path('library/new/', PostCreateView.as_view(), name='post-create'),
    path('detail/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
    path('library/<int:pk>/update/', PostUpdateView.as_view(), name='post-update'),
    path('library/<int:pk>/del/', PostDeleteView.as_view(), name='post-delete'),
    path('library/<int:postid>/preference/<int:userpreference>', postpreference, name='postpreference'),

]

library/models.py
from distutils.command.upload import upload
from django.db import models
from django.utils import timezone
from accounts.models import MyUser
from django.urls import reverse


class Post(models.Model):
    title = models.TextField(max_length=1000)
    description = models.TextField(max_length=1000)
    code_snippet = models.TextField(max_length=1000)
    date_posted = models.DateTimeField(default=timezone.now)
    category = models.ForeignKey('PostCategory', on_delete=models.CASCADE)
    author = models.ForeignKey(MyUser, on_delete=models.CASCADE)
    likes= models.IntegerField(default=0)
    dislikes= models.IntegerField(default=0)
    downloadnumber = models.IntegerField(default=0)
    github = models.URLField(max_length=500, null=True, blank=True,)
    download = models.URLField(max_length=500, null=True, blank=True,)
    images = models.ImageField(upload_to='library_images', blank=True)

    
    def __str__(self):
        return self.title

    @property
    def number_of_comments(self):
        return Comment.objects.filter(post_connected=self).count()


class PostCategory(models.Model):
    name = models.CharField(verbose_name='name', max_length=150, default="Name")
    images = models.ImageField(upload_to='library_images', blank=True)
    parent = models.ForeignKey('self', blank=True, null=True, related_name='child', on_delete=models.CASCADE)
    class Meta:
        unique_together = ('name', 'parent',)
        verbose_name_plural = "categories"

    def __str__(self):
        full_path = [self.name]
        k = self.parent
        while k is not None:
            full_path.append(k.name)
            k = k.parent

        return ' -> '.join(full_path[::-1])

class Comment(models.Model):
    content = models.TextField(max_length=150)
    date_posted = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(MyUser, on_delete=models.CASCADE)
    post_connected = models.ForeignKey(Post, on_delete=models.CASCADE)

    def __str__(self):
        return self.post_connected.title


class Preference(models.Model):
    user= models.ForeignKey(MyUser, on_delete=models.CASCADE)
    post= models.ForeignKey(Post, on_delete=models.CASCADE)
    value= models.IntegerField()
    date= models.DateTimeField(auto_now= True)

    def __str__(self):
        return str(self.user) + ':' + str(self.post) +':' + str(self.value)

    class Meta:
       unique_together = ("user", "post", "value")

library/forms.py
from django import forms
from .models import Comment


class NewCommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']

library/views.py
from django.shortcuts import render, get_object_or_404, redirect
from library.models import Post, Comment, Preference, PostCategory
from users.models import UserProfile
from django.http import HttpResponseRedirect
from accounts.models import MyUser
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.db.models import Count
from .forms import NewCommentForm
from django.contrib.auth.decorators import login_required

def is_users(post_user, logged_user):
    return post_user == logged_user

PAGINATION_COUNT = 3

# Create your views here.
class LibraryView(LoginRequiredMixin, ListView):
    model = PostCategory
    template_name = "library/home.html"
    context_object_name = 'post_categories'
#     categories = PostCategory.objects.filter(parent__isnull=True)
    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data['categories'] = PostCategory.objects.all()
        return data


class PostListView(LoginRequiredMixin, ListView):
    model = Post
    template_name = 'library/index.html'
    context_object_name = 'posts'
    ordering = ['-date_posted']
    paginate_by = PAGINATION_COUNT
    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data['preference'] = Preference.objects.all()
        return data
    def get_queryset(self):
        category = get_object_or_404(PostCategory, name=self.kwargs.get('name'))
        return Post.objects.filter(category=category)




class PostDetailView(DetailView):
    model = Post
    template_name = 'library/library_detail.html'
    context_object_name = 'post'

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        comments_connected = Comment.objects.filter(post_connected=self.get_object()).order_by('-date_posted')
        data['comments'] = comments_connected
        data['form'] = NewCommentForm(instance=self.request.user)
        return data

    def post(self, request, *args, **kwargs):
        new_comment = Comment(content=request.POST.get('content'),
                              author=self.request.user,
                              post_connected=self.get_object())
        new_comment.save()

        return self.get(self, request, *args, **kwargs)

class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    template_name = 'library/post_delete.html'
    context_object_name = 'post'
    success_url = '/library'

    def test_func(self):
        return is_users(self.get_object().author, self.request.user)


class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    fields = ['title','description','code_snippet','github','download','images']
    template_name = 'library/post_new.html'
    success_url = '/library'

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data['tag_line'] = 'Add a new post'
        return data


class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    fields = ['title','description','code_snippet','github','download','images']
    template_name = 'library/post_new.html'
    success_url = '/library'

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        return is_users(self.get_object().author, self.request.user)

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data['tag_line'] = 'Edit a post'
        return data

# Like Functionality====================================================================================

@login_required
def postpreference(request, postid, userpreference):
        
        if request.method == "POST":
                eachpost= get_object_or_404(Post, id=postid)

                obj=''

                valueobj=''

                try:
                        obj= Preference.objects.get(user= request.user, post= eachpost)

                        valueobj= obj.value #value of userpreference


                        valueobj= int(valueobj)

                        userpreference= int(userpreference)
                
                        if valueobj != userpreference:
                                obj.delete()


                                upref= Preference()
                                upref.user= request.user

                                upref.post= eachpost

                                upref.value= userpreference


                                if userpreference == 1 and valueobj != 1:
                                        eachpost.likes += 1
                                        eachpost.dislikes -=1
                                elif userpreference == 2 and valueobj != 2:
                                        eachpost.dislikes += 1
                                        eachpost.likes -= 1
                                

                                upref.save()

                                eachpost.save()
                        
                        
                                context= {'eachpost': eachpost,
                                  'postid': postid}

                                return HttpResponseRedirect(request.META.get('HTTP_REFERER',  '/'))

                        elif valueobj == userpreference:
                                obj.delete()
                        
                                if userpreference == 1:
                                        eachpost.likes -= 1
                                elif userpreference == 2:
                                        eachpost.dislikes -= 1

                                eachpost.save()

                                context= {'eachpost': eachpost,
                                  'postid': postid}

                                return HttpResponseRedirect(request.META.get('HTTP_REFERER',  '/'))
                                
                        
        
                
                except Preference.DoesNotExist:
                        upref= Preference()

                        upref.user= request.user

                        upref.post= eachpost

                        upref.value= userpreference

                        userpreference= int(userpreference)

                        if userpreference == 1:
                                eachpost.likes += 1
                        elif userpreference == 2:
                                eachpost.dislikes +=1

                        upref.save()

                        eachpost.save()                            


                        context= {'eachpost': eachpost,
                          'postid': postid}

                        return HttpResponseRedirect(request.META.get('HTTP_REFERER',  '/'))


        else:
                eachpost= get_object_or_404(Post, id=postid)
                context= {'eachpost': eachpost,
                          'postid': postid}

                return HttpResponseRedirect(request.META.get('HTTP_REFERER',  '/'))

templates/library/home.html
{% extends 'base2.html'%}
{% load static %}
{% block content %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

<link rel="stylesheet" href="{%static 'css/library_home.css' %}"/>
    <div class="container">
        <div class="top">
            <img class=' img img-fluid' src="{%static 'images/library_image.png'%}"/>
            <div class="lower ">
                <span class="one">Sort by: </span>
                <button class="btn text-primary btn-outline-info">Most Popular</button>
                <button class="btn text-light btn-outline-light ml-4">Alphabetical Order</button>
            </div>
        </div>
        {% for category in post_categories %}
            <div class="m-auto mt-5 pt-5 cot-div" >
                <a class="row div-hover" href="{% url 'library:library-category' category.name %}" class="row">
                    <div class="col-md-6 ">
                        <img class="m-auto images" src="{{ category.images.url }}">
                    </div> 
                    <h1 class="m-auto col-md-6 text">{{ category.name }}</h1>                    
                </a>
            <div>

        {% endfor %}
    </div>
{% endblock %}

templates/library/index.html
{% extends 'base2.html' %}
{% load static %}
{%block extra_css %}
<head>
    <link rel="stylesheet" href="https://unpkg.com/flowbite@1.5.2/dist/flowbite.min.css" />
    <script src="https://unpkg.com/flowbite@1.5.2/dist/flowbite.js"></script>
    <script src="https://cdn.tailwindcss.com"></script>
    <!-- <link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css"> -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{%static 'css/library_style.css' %}">
</head>
{% endblock%}
<body>
{% block content  %}


     <title>Document</title>
    <main>
        <!-- sevelte section -->
        <section >
            <div id="main " class="w-[90%] m-auto p-5">
            {% for post in posts %}
                <div id="sevelte"  class="box  m-auto">
                    <!-- top -->
                    <div class="container m-auto p-10 lg:p-10 flex justify-evenly">
                        <div class="w-[150px] lg:mt-[-20px] lg:w-[300px]  ">
                            <img src="{{post.images.url}}" alt="">
                        </div>
                        <div class="div hidden lg:flex mt-auto "></div>
                        <div>
                           <a href="{%url 'library:post-detail' post.id%}"> 
                                <div class="  w-[300px] sm:w-[250px] text-center  lg:text-2xl font-bold ">
                                    <h1 class="">{{post.title}}</h1>
                                </div>
                            </a>
                            <p class="pt-3">{{post.description|truncatewords:20}}</p>
                        </div>

                    </div>
                </div>
            {% endfor %}
            </section>       
    </main>
{% endblock %}
</body>

templates/library/library_detail.html
{% extends 'base2.html' %}
{% load static %}
{% block content %}
    <link rel="stylesheet" href="{%static 'css/library_detail.css' %}">
    <div class="container whole">
        <div>
            <img class="image-fluid image1" src="{{post.images.url}}" />

            <h2 class="text-center p-3">{{post.title}}</h2>

            <span class="text">{{post.description}}</span>
            <div class="code_snippet">
                <pre>
                    <code>
                        {{post.code_snippet}}
                    </code>
                </pre>
            </div>
        </div>
        <hr>
        {% if user.is_authenticated%}
            <div class="row icons">
                <a class="col-3" href="{{post.github}}"><img class="icon-img" src="{%static 'images/github.png'%}"></a>
                <a class="col-3" href="{{post.download}}"><img class="icon-img" src="{%static 'images/web.png'%}"></a>
                <!-- Like Buttons Here -->
                <a class="col-1" href="#" onClick="document.getElementById('likebutton').submit()"><span id="thumbsUp" class="icon-img iconify color" data-icon="fa-regular:thumbs-up"></span></a> {{post.likes}}   
                <a class="col-2" href="#" onClick="document.getElementById('dislikebutton').submit()"><span id="thumbsDown" class="icon-img iconify color" data-icon="fa-regular:thumbs-down"></span></a> {{post.dislikes}}
                <form id="likebutton" method="POST" action="{% url 'library:postpreference' post.id 1 %}">
                        {% csrf_token %}
                        <input type="hidden">
                </form>

                <form id="dislikebutton" method="POST" action="{% url 'library:postpreference' post.id 2 %}">
                    {% csrf_token %}
                    <input type="hidden">
                </form>
            </div>
            <hr>
            <form action="" method='POST' class="comment_section">
                {%csrf_token%}
                <div class="form-group">
                    <input type="text" name="content" class="form-control" id="formGroupExampleInput" placeholder="Comment..">
                </div>
                <button class="btn btn-primary mt-3" type="submit"> Comment</button>
            </form>
            <hr>
            {% if comments %}
                {% for com in comments %}
                    <p>{{com.content}}</P>
                    <small>{{com.author}}</small>
                    <hr>
                {% endfor %}
            {% else %}
            <div class="alert alert-secondary" role="alert">
                No comment yet add one ..
            </div>
            {% endif %}
        {% else %}
        <div class="alert alert-secondary" role="alert">
            <a href="{'accounts:signup}">Signup</a> for more information
        </div>
        {% endif %}
    </div>
    {% comment %} <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script> {% endcomment %}
    <script src="https://code.iconify.design/2/2.2.1/iconify.min.js"></script>
    <script src="{%static 'js/preference.js' %}"></script>
{% endblock %}

templates/library/post_delete.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    <form method="POST">
        {% csrf_token %}
        <fieldset>
            Do you really want to delete
        </fieldset>
        <p>
           {{ post.content }}
        </p>
        <div class="form-group">
            <button type="submit">Yes</button>
        </div>
    </form>
</div>
{% endblock content %}

templates/library/post_detail.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    <h3>
        Post
    </h3>
   <article>
        <div>
            <div>
               <div>
                   <img src="{{ post.author.userprofile.image.url }}" width="20px">
                   {% comment %} <a class="mr-2 white-important" href="{% url 'user-posts' post.author %}"> {% endcomment %}
                       {{ post.author }}
                   </a>
               </div>
               <div>
                   {% if post.author == user %}
                        <a href="{% url 'library:post-delete' post.id %}">clear</a></a>
                        <a href="{% url 'library:post-update' post.id %}">update</a></a>
                    {%  endif %}
               </div>
           </div>
            <div></div>
            <a>
                <p>
                    {{ post.title }}
                </p>
                <p>
                    {{ post.description }}
                </p>
                <p>
                    Code Snippet
                    {{ post.code_snippet }}
                </p>
                
                <p>
                    <a href="{{ post.github }}">Github</a>
                    
                </p>
                <p>
                    <a href="{{ post.download }}">Download</a>
                </p>
                <p>
                    
                    {{ post.images }}
                </p>
                <p>
                       
                    {{ post.date_posted | date:"H:i l, d.m.y" }}

                </p>
                <i>Number of Downloads</i> {{post.downloadnumber}}

                    <div>
                        <div>
                            <small>

                                <!-- Like Buttons Here -->
                                <a href="#" onClick="document.getElementById('likebutton').submit()"><i class="fas fa-thumbs-up">Like</i></a> {{post.likes}}   |   <a href="#" onClick="document.getElementById('dislikebutton').submit()"><i class="fas fa-thumbs-down">dislike</i></a> {{post.dislikes}}


                                <form id="likebutton" method="POST" action="{% url 'library:postpreference' post.id 1 %}">
                                {% csrf_token %}
                                <input type="hidden">
                                </form>

                                <form id="dislikebutton" method="POST" action="{% url 'library:postpreference' post.id 2 %}">
                                {% csrf_token %}
                                <input type="hidden">
                                </form>


                            </small>
                       </div>
                        
                    </div>

                
                
            

                <small>
                    {{ post.date_posted | date:"H:i l, d.m.y" }}
                </small>
            </a>
        </div>
   </article>
    <div>
        <div>
         <h3>
             Comments
         </h3>
        {% for comment in comments %}
            <article>
                <div>
                <div>
                   <div>
                       <img src="{{ comment.author.profile.image.url }}" width="20px">
                       {% comment %} <a href="{% url 'user-posts' comment.author.username %}"> {% endcomment %}
                           {{ comment.author }}
                       </a>
                   </div>
               </div>
                <div></div>
                <a>
                    <p>
                        {{ comment.content }}
                    </p>

                    <small>
                        {{ comment.date_posted | date:"H:i l, d.m.y" }}
                    </small>
                </a>
            </div>
            </article>
        {% endfor %}
        </div>
        {% if user is not None %}
            <div>
                <h3>
                    Add a comment
                </h3>
                <form method="POST">
                    {% csrf_token %}
                    <fieldset class="form-group">
                        {{ form }}
                    </fieldset>
                    <div class="form-group">
                        <button type="submit">Submit comment</button>
                    </div>
                </form>
            </div>
        {% endif %}
    </div>
  </div>
{% endblock content %}

templates/library/post_new.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    <h3 class="white-important">
        {{  tag_line }}
    </h3>
    <form method="POST" class="col-12 col-md-6 no-padding pr-3 pr-md-0">
        {% csrf_token %}
        <fieldset class="form-group">
            {{ form }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-primary" type="submit">Submit changes</button>
        </div>
    </form>
</div>
{% endblock content %}